from pathutil import *

tgtroot = 'tsload-standalone'
target = 'tsexperiment'

Import('env')

cmd = env.Clone()

def InstallExperiment(experiment_name):
    for file in Dir(experiment_name).glob('*'):
        cmd.Depends(tsexperiment,  file)
        cmd.InstallTarget(tgtroot, PathJoin(cmd['INSTALL_VAR'], experiment_name), file)

cmd.Macroses('NO_JSON')

cmd.AddDeps(('lib', 'libjson'),
            ('lib', 'libtscommon'),
            ('lib', 'libtsjson'),
            ('lib', 'libtsobj'),
            ('lib', 'libtsfile'),  
            ('lib', 'libhostinfo'), 
            ('lib', 'libtsload'))
objects = cmd.CompileProgram()
tsexperiment = cmd.Program(target, objects)

i_tsexperiment = cmd.InstallTarget(tgtroot, cmd['INSTALL_BIN'], tsexperiment)

InstallExperiment('sample')