from pathutil import *

tgtroot = 'tsload-core'
tgtdir = 'bin'
target = 'tsfutil'

Import('env')

cmd = env.Clone()
cmd.UseSubsystems('log', 'mempool', 'tsfile')

objects = cmd.CompileProgram()
tsgenuuid = cmd.LinkProgram(target, objects)

cmd.InstallTarget(tgtroot, cmd['INSTALL_BIN'], tsgenuuid)