from pathutil import *

tgtroot = 'tsload-core'
tgtdir = 'bin'
target = 'tsfutil'

Import('env')

cmd = env.Clone()

cmd.PreparePlatform()

cmd.AddDeps(('lib', 'libtscommon'),
            ('lib', 'libtsjson'),
            ('lib', 'libtsfile'))

objects = cmd.CompileProgram()
tsgenuuid = cmd.Program(target, objects)

cmd.InstallTarget(tgtroot, cmd['INSTALL_BIN'], tsgenuuid)