import sys

from pathutil import PathJoin

tgtroot = 'tsload-core'
target = 'libtsobj'

Import('env')

lib = env.Clone()

lib.Append(CCFLAGS = ['-O2'])

# lib.PreparePlatform()
lib.UseSubsystems('mempool', 'json')

TSObjGenBuilder = Builder(action = Action('%s $TSLOADPATH/tools/gentsobjapi.py $SOURCE > $TARGET' % (sys.executable),
                                          lib.PrintCommandLine('GENTSOBJAPI')))
lib.Append(BUILDERS = {'TSObjGenBuilder': TSObjGenBuilder})

tsobjgen_path = lib.BuildDir(PathJoin('include', 'tsload', 'obj', 'tsobjgen.h'))
tsobjgen_h = lib.TSObjGenBuilder(tsobjgen_path, 'tsobjgen.in')
lib.Depends('include/tsobj.h', tsobjgen_h)
lib.InstallTarget(tgtroot, PathJoin(lib['INSTALL_INCLUDE'], 'tsload', 'obj'), tsobjgen_h)

objects = lib.CompileSharedLibrary()
library = lib.LinkSharedLibrary(target, objects)

lib.InstallTarget(tgtroot, lib['INSTALL_LIB'], library)