from pathutil import *

tgtroot = 'tsload-core'
tgtdir = 'bin'
target = 'tshostinfo'

Import('env')

cmd = env.Clone()

cmd.AddDeps(('lib', 'libtscommon'),
            ('lib', 'libtsjson'),
            ('lib', 'libtsobj'),
            ('lib', 'libhostinfo'))

objects = cmd.CompileProgram()
tshostinfo = cmd.Program(target, objects)

cmd.InstallTarget(tgtroot, cmd['INSTALL_BIN'], tshostinfo)