from pathutil import *

tgtroot = 'tsload-core'
tgtdir = 'bin'
target = 'tshostinfo'

Import('env')

cmd = env.Clone()

cmd.UseSubsystems('mempool', 'sched', 'tsobj', 'hi_obj')

objects = cmd.CompileProgram()
tshostinfo = cmd.LinkProgram(target, objects)

cmd.InstallTarget(tgtroot, cmd['INSTALL_BIN'], tshostinfo)