from pathutil import *

_target = 'run-tsload'

Import('env')

def InstallExperiment(experiment_name):
    for file in Dir(experiment_name).glob('*'):
        cmd.Depends(run_tsload,  file)
        cmd.InstallTarget(PathJoin(cmd['INSTALL_VAR'], experiment_name), file)

cmd = env.Clone()

cmd.AddDeps(('lib', 'libtsagent'), 
            ('lib', 'libtscommon'), 
            ('lib', 'libjson'),
            ('lib', 'libtsfile'),  
            ('lib', 'libhostinfo'), 
            ('lib', 'libtsload'))
objects = cmd.CompileProgram()
run_tsload = cmd.Program(_target, objects)

i_run_tsload = cmd.InstallTarget(cmd['INSTALL_BIN'], run_tsload)

# Install test experiment files
InstallExperiment('simpleio')
InstallExperiment('busy_wait')

# Install request schema file
request_schema = 'request-schema.json'
cmd.Depends(run_tsload, request_schema)
cmd.InstallTarget(cmd['INSTALL_VAR'], request_schema)
    