tgtroot = 'tsload-core'
target = 'libhostinfo'

Import('env')

lib = env.Clone()

lib.PreparePlatform('include/hostinfo')

if lib.SupportedPlatform('solaris'):
    lib.Append(LIBS = ['diskmgt', 'lgrp', 'nvpair', 'kstat', 'dladm'])

if lib.SupportedPlatform('win'):
    lib.Append(LIBS = ['setupapi', 'user32', 'advapi32', 'wbemuuid', 'comsuppw', 
                       'iphlpapi', 'Ws2_32'])

lib.UseSubsystems('mempool', 'tsobj')

extra_sources = []
if lib.SupportedPlatform('win'):
    extra_sources = ['plat/win/wmi.cpp']

objects = lib.CompileSharedLibrary(extra_sources)
library = lib.LinkSharedLibrary(target, objects)

if lib.SupportedPlatform('linux') and GetOption('lvm2'):
	SConscript('lvm2/SConscript', 'lib')
if lib.SupportedPlatform('posix') and GetOption('zfs'):
	SConscript('zfs/SConscript', 'lib')

lib.InstallTarget(tgtroot, lib['INSTALL_LIB'], library)