import os

tgtroot = 'tsload-standalone'
tgtdir = 'bin'
target = 'jsonbench'

Import('env')

cmd = env.Clone()

if cmd.SupportedPlatform('posix'):
    cmd.Append(LIBS = ['c'])    

cmd.AddDeps(('lib', 'libtscommon'),
            ('lib', 'libjson'),
            ('lib', 'libtsjson'))
jsonbench = cmd.Program(target, Glob("*.c"))

cmd.InstallTarget(tgtroot, cmd['INSTALL_BIN'], jsonbench)