tgtroot = 'tsload-core'
target = 'libtsjson'

Import('env')

lib = env.Clone()

# lib.Append(CCFLAGS = ['-O2'])

# lib.PreparePlatform()
lib.UseSubsystems('mempool')

vlib = lib.Clone()
objects = vlib.CompileSharedLibrary()
library = vlib.LinkSharedLibrary(target, objects, versioned=True)
vlib.InstallTarget(tgtroot, lib['INSTALL_LIB'], library)