tgtroot = 'tsload-core'
target = 'libtsjson'

Import('env')

lib = env.Clone()

lib.Macroses('LIBTSJSON')
# lib.Append(CCFLAGS = ['-O2'])

# lib.PreparePlatform()
lib.UseSubsystems('mempool')

objects = lib.CompileSharedLibrary()
library = lib.LinkSharedLibrary(target, objects)

lib.InstallTarget(tgtroot, lib['INSTALL_LIB'], library)