import os

PathJoin = os.path.join

tgtroot = 'tsload-core'
target = 'libtsload'

Import('env')

lib = env.Clone()

if lib.SupportedPlatform('win'):
    lib.Append(LIBS = ['advapi32']) 

if GetOption('fast_randgen'):
    lib.Macroses('TSLOAD_RANDGEN_FAST')

lib.AddDeps(('lib', 'libjson'), 
            ('lib', 'libtscommon'), 
            ('lib', 'libhostinfo'))

lib.PreparePlatform()
objects = lib.CompileSharedLibrary(Glob("src/disp/*.c") + Glob("src/randgen/*.c") + \
                                   Glob("src/tpdisp/*.c"))

etrace_files, man_files = env.PreprocessETrace(['src/workload.c'] + objects, 
                                                target + lib['SHLIBSUFFIX'])

library = lib.LinkSharedLibrary(target, objects + etrace_files)

lib.InstallTarget(tgtroot, lib['INSTALL_LIB'], library)
lib.InstallTarget(tgtroot, lib['INSTALL_SHARE'], man_files)