tgtroot = 'tsload-core'
target = 'libtsfile'

Import('env')

lib = env.Clone()
lib.UseSubsystems('log', 'mempool', 'json')

vlib = lib.Clone()
objects = vlib.CompileSharedLibrary()
library = vlib.LinkSharedLibrary(target, objects, versioned=True)

vlib.InstallTarget(tgtroot, lib['INSTALL_LIB'], library)