tgtroot = 'tsload-core'
target = 'libtsfile'

Import('env')

lib = env.Clone()
lib.UseSubsystems('log', 'mempool', 'json')

objects = lib.CompileSharedLibrary()
library = lib.LinkSharedLibrary(target, objects)

lib.InstallTarget(tgtroot, lib['INSTALL_LIB'], library)