tgtroot = 'tsload-core'
target = 'libtsfile'

Import('env')

lib = env.Clone()
lib.AddDeps(('lib', 'libtscommon'), ('lib', 'libtsjson'))

objects = lib.CompileSharedLibrary()
library = lib.LinkSharedLibrary(target, objects)

lib.InstallTarget(tgtroot, lib['INSTALL_LIB'], library)